version: "3.1"
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    env_file:
     - .env
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - ${DB_MONGO_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE : ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  api:
    image: node:latest
    container_name: api
    env_file:
     - .env
    depends_on:
      - mysql-db
      - mongo
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      bash -c "yarn dev"
## bash -c "node ace migration:run && node ace db:seed && yarn build --ignore-ts-errors && cp .env build && cd build && yarn install --production && node server.js"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
